export enum TYPES {
	GET_PAYMENT_METHOD_PENDING = "GET_PAYMENT_METHOD_PENDING",
	GET_PAYMENT_METHOD_SUCCESS = "GET_PAYMENT_METHOD_SUCCESS",
	GET_PAYMENT_METHOD_ERROR = "GET_PAYMENT_METHOD_ERROR",
	CLEAR_DATA_PAYMENT_METHOD = "CLEAR_DATA_PAYMENT_METHOD"
}
