export enum TYPES {
	GET_NOTIFICATION_PENDING = "GET_NOTIFICATION_PENDING",
	GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS",
	GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR",
	SET_NOTIFICATION_UNMOUNT = "SET_NOTIFICATION_UNMOUNT"
}
