export enum TYPES {
	GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING",
	GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS",
	GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR",
	SET_PRODUCT_UNMOUNT = "SET_PRODUCT_UNMOUNT"
}
